### ISSUE TITLE
Hitting dkms bug fixed upstream

### ISSUE THREAD

**Issue by GICodeWarrior** [zfsonlinux/pkg-zfs#195]
Would it be possible for the dkms package to be updated?

I am hitting this bug that was fixed upstream: https://bugs.launchpad.net/ubuntu/+source/dkms/+bug/1499842

**Comment by rincebrain** [comment]
That bug, unless I'm bad at reading comprehension, is in DKMS, the tool for building kernel modules dynamically, not any packaging.

This repo has many things, but DKMS is not one of them.

If you were trying to communicate with someone about, say, Debian or another distro needing to package the bugfix, this is also not the correct location for that.

**Comment by GICodeWarrior** [comment]
Thanks.  Do you know where to file issues on the ZFS stable PPA?

https://launchpad.net/~zfs-native/+archive/ubuntu/stable?field.series_filter=trusty

That is the repo with the old DKMS package.

**Comment by rincebrain** [comment]
On Ubuntu, presumably you'd not want a PPA any more, just the dist-provided packages, so https://launchpad.net/ubuntu/+source/zfs-linux/+bugs.

If you have a problem with a specific PPA, you'd presumably follow the instructions on the PPA page. For example, in your link, it suggests contacting the team responsible for maintaining that PPA, and the contact page for them can be found at https://launchpad.net/~zfs-native/+contactuser.

**Comment by GICodeWarrior** [comment]
Thanks.  The Ubuntu-provided packages are not available in the current LTS releases.

Based on the README.md for this repo, "ZoL packages at https://launchpad.net/~zfs-native (the PPA) and http://archive.zfsonlinux.org/debian/ are built from this repository using the git-buildpackage tool."

Based on the readme and the DKMS packaging scripts present in this repo, this does seem like the correct place to report this issue.

https://github.com/zfsonlinux/pkg-zfs/tree/master/ubuntu/trusty/debian

**Comment by dajhorn** [comment]
@GICodeWarrior, you are reporting in the correct place, and the DKMS package should indeed be updated.

**Comment by rsyring** [comment]
#219 is for a bug with building the zfs module, but it also contains evidence that DKMS is still out of date:

```
cleaning build area....
make KERNELRELEASE=4.4.0-59-generic....................(bad exit status: 2)
Traceback (most recent call last):
  File "/usr/share/apport/package-hooks/dkms_packages.py", line 97, in <module>
    with open(apport.fileutils.make_report_path(report), 'wb') as f:
AttributeError: 'module' object has no attribute 'make_report_path'
Error! Bad return status for module build on kernel: 4.4.0-59-generic (x86_64)
Consult /var/lib/dkms/zfs/0.6.5.7/build/make.log for more information.
```

The bug with `make_report_path()` as been fixed upstream in 2.2.0.3-1.1ubuntu5.14.04.**5**:

https://bugs.launchpad.net/ubuntu/+source/dkms/+bug/1499842

But dkms in the ppa is still running 2.2.0.3-1.1ubuntu5.14.04.**1**

**Comment by jknockaert** [comment]
@rsyring This one should be fixed now. @dajhorn I guess this one can be closed now.

**Comment by rsyring** [comment]
I can confirm that dkms is now showing up as 2.2.0.3-1.1ubuntu5.14.04.9.

Thank you!

**Comment by dajhorn** [comment]
Closing as resolved because distro is backporting.
